"""
can one block of except statement handle multiple exception ?

yes, a single block of except statement in python can handle multiple exception..


"""